services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dtransfert
      POSTGRES_PASSWORD: dtransfert
      POSTGRES_DB: dtransfert
    ports:
      - "5432:5432"
    volumes:
      - dtransfert_postgres_data:/var/lib/postgresql/data

volumes:
  dtransfert_postgres_data:
