"""add wallet_id to transfers

Revision ID: 0118c9af488b
Revises: 469143998093
Create Date: 2026-07-10 15:04:28.397437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0118c9af488b'
down_revision: Union[str, Sequence[str], None] = '469143998093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('wallet_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transfers', 'wallets', ['wallet_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'wallet_id')
    # ### end Alembic commands ###
