"""phase3 wallets and movements

Revision ID: 012c10ff7436
Revises: 9e821a48c523
Create Date: 2026-07-04 12:55:15.708583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012c10ff7436'
down_revision: Union[str, Sequence[str], None] = '9e821a48c523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'MOBILE_MONEY', 'BANK', 'OTHER', name='wallettype', native_enum=False, length=16), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='walletstatus', native_enum=False, length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_wallet_company_code')
    )
    op.create_index(op.f('ix_wallets_company_id'), 'wallets', ['company_id'], unique=False)
    op.create_table('wallet_movements',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='movementdirection', native_enum=False, length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_movements_source_id'), 'wallet_movements', ['source_id'], unique=False)
    op.create_index(op.f('ix_wallet_movements_wallet_id'), 'wallet_movements', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_movements_wallet_id'), table_name='wallet_movements')
    op.drop_index(op.f('ix_wallet_movements_source_id'), table_name='wallet_movements')
    op.drop_table('wallet_movements')
    op.drop_index(op.f('ix_wallets_company_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
