"""phase6 entries

Revision ID: 1d2b3bca5059
Revises: 9242c0f4ae52
Create Date: 2026-07-04 13:27:32.537157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2b3bca5059'
down_revision: Union[str, Sequence[str], None] = '9242c0f4ae52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('UNALLOCATED', 'PARTIALLY_ALLOCATED', 'ALLOCATED', 'CONSUMED', 'REJECTED', 'CANCELLED', name='entrystatus', native_enum=False, length=24), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_company_id'), 'entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_entries_reference'), 'entries', ['reference'], unique=True)
    op.create_table('entry_allocations',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('TRANSFER', 'PAYMENT', name='entryallocationtargettype', native_enum=False, length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_allocations_entry_id'), 'entry_allocations', ['entry_id'], unique=False)
    op.create_table('entry_lines',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_lines_entry_id'), 'entry_lines', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_lines_entry_id'), table_name='entry_lines')
    op.drop_table('entry_lines')
    op.drop_index(op.f('ix_entry_allocations_entry_id'), table_name='entry_allocations')
    op.drop_table('entry_allocations')
    op.drop_index(op.f('ix_entries_reference'), table_name='entries')
    op.drop_index(op.f('ix_entries_company_id'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
