"""add status to proofs

Revision ID: 2b802e2505d4
Revises: 9c101344d01f
Create Date: 2026-07-07 15:54:11.896508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b802e2505d4'
down_revision: Union[str, Sequence[str], None] = '9c101344d01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'proofs',
        sa.Column(
            'status',
            sa.Enum('PENDING', 'VALIDATED', 'REJECTED', name='proofstatus', native_enum=False, length=16),
            server_default='PENDING',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proofs', 'status')
    # ### end Alembic commands ###
