"""add exchange_rate to national_operations

Revision ID: 38bacc5a0669
Revises: c42c18998f51
Create Date: 2026-07-07 16:43:28.200891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38bacc5a0669'
down_revision: Union[str, Sequence[str], None] = 'c42c18998f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_operations', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('national_operations', 'exchange_rate')
    # ### end Alembic commands ###
