"""reference format per company daily sequence

Revision ID: 469143998093
Revises: 38bacc5a0669
Create Date: 2026-07-09 14:44:24.191236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469143998093'
down_revision: Union[str, Sequence[str], None] = '38bacc5a0669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_reference'), table_name='entries')
    op.create_index(op.f('ix_entries_reference'), 'entries', ['reference'], unique=False)
    op.create_unique_constraint('uq_entries_company_reference', 'entries', ['company_id', 'reference'])
    op.drop_index(op.f('ix_national_operations_reference'), table_name='national_operations')
    op.create_index(op.f('ix_national_operations_reference'), 'national_operations', ['reference'], unique=False)
    op.create_unique_constraint('uq_national_operations_company_reference', 'national_operations', ['company_id', 'reference'])
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    op.create_unique_constraint('uq_payments_company_reference', 'payments', ['company_id', 'reference'])
    op.add_column('supplier_balance_movements', sa.Column('company_id', sa.UUID(), nullable=True))
    op.execute(
        """
        UPDATE supplier_balance_movements
        SET company_id = suppliers.company_id
        FROM suppliers
        WHERE suppliers.id = supplier_balance_movements.supplier_id
        """
    )
    op.alter_column('supplier_balance_movements', 'company_id', nullable=False)
    op.drop_index(op.f('ix_supplier_balance_movements_reference'), table_name='supplier_balance_movements')
    op.create_index(op.f('ix_supplier_balance_movements_reference'), 'supplier_balance_movements', ['reference'], unique=False)
    op.create_index(op.f('ix_supplier_balance_movements_company_id'), 'supplier_balance_movements', ['company_id'], unique=False)
    op.create_unique_constraint('uq_supplier_balance_movements_company_reference', 'supplier_balance_movements', ['company_id', 'reference'])
    op.create_foreign_key(
        'fk_supplier_balance_movements_company_id_companies',
        'supplier_balance_movements', 'companies', ['company_id'], ['id'], ondelete='CASCADE',
    )
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=False)
    op.create_unique_constraint('uq_transfers_company_reference', 'transfers', ['company_id', 'reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transfers_company_reference', 'transfers', type_='unique')
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=True)
    op.drop_constraint(
        'fk_supplier_balance_movements_company_id_companies', 'supplier_balance_movements', type_='foreignkey'
    )
    op.drop_constraint('uq_supplier_balance_movements_company_reference', 'supplier_balance_movements', type_='unique')
    op.drop_index(op.f('ix_supplier_balance_movements_company_id'), table_name='supplier_balance_movements')
    op.drop_index(op.f('ix_supplier_balance_movements_reference'), table_name='supplier_balance_movements')
    op.create_index(op.f('ix_supplier_balance_movements_reference'), 'supplier_balance_movements', ['reference'], unique=True)
    op.drop_column('supplier_balance_movements', 'company_id')
    op.drop_constraint('uq_payments_company_reference', 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.drop_constraint('uq_national_operations_company_reference', 'national_operations', type_='unique')
    op.drop_index(op.f('ix_national_operations_reference'), table_name='national_operations')
    op.create_index(op.f('ix_national_operations_reference'), 'national_operations', ['reference'], unique=True)
    op.drop_constraint('uq_entries_company_reference', 'entries', type_='unique')
    op.drop_index(op.f('ix_entries_reference'), table_name='entries')
    op.create_index(op.f('ix_entries_reference'), 'entries', ['reference'], unique=True)
    # ### end Alembic commands ###
