"""add settles_debt to payments

Revision ID: 4ae3bbf04179
Revises: 71c451ee1b4c
Create Date: 2026-07-13 14:58:30.169680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae3bbf04179'
down_revision: Union[str, Sequence[str], None] = '71c451ee1b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payments', sa.Column('settles_debt', sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'settles_debt')
    # ### end Alembic commands ###
