"""phase8 payments

Revision ID: 534f4ad3c025
Revises: b7adc6877932
Create Date: 2026-07-04 13:45:35.531443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534f4ad3c025'
down_revision: Union[str, Sequence[str], None] = 'b7adc6877932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('collaborative_rate_used', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('converted_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('proof_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_collaboration_id'), 'payments', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_table('payment_status_history',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='paymentstatus', native_enum=False, length=16), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_status_history_payment_id'), 'payment_status_history', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_status_history_payment_id'), table_name='payment_status_history')
    op.drop_table('payment_status_history')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_collaboration_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
