"""add require_company_approval to platform_settings

Revision ID: 84ddfbfe8744
Revises: 2b802e2505d4
Create Date: 2026-07-07 16:27:31.285108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ddfbfe8744'
down_revision: Union[str, Sequence[str], None] = '2b802e2505d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'platform_settings',
        sa.Column('require_company_approval', sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'require_company_approval')
    # ### end Alembic commands ###
