"""phase5 collaborations and rates

Revision ID: 9242c0f4ae52
Revises: a127642fd303
Create Date: 2026-07-04 13:17:21.267808

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.permission_codes import PERMISSION_DESCRIPTIONS, PermissionCode


# revision identifiers, used by Alembic.
revision: str = '9242c0f4ae52'
down_revision: Union[str, Sequence[str], None] = 'a127642fd303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('initiator_company_id', sa.UUID(), nullable=False),
    sa.Column('target_company_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'SUSPENDED', 'ARCHIVED', name='collaborationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('current_rate_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiator_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_initiator_company_id'), 'collaborations', ['initiator_company_id'], unique=False)
    op.create_index(op.f('ix_collaborations_target_company_id'), 'collaborations', ['target_company_id'], unique=False)
    op.create_table('collaboration_rate_history',
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('old_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('new_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', name='rateproposalstatus', native_enum=False, length=16), nullable=False),
    sa.Column('proposed_by_company_id', sa.UUID(), nullable=False),
    sa.Column('decided_by_company_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaboration_rate_history_collaboration_id'), 'collaboration_rate_history', ['collaboration_id'], unique=False)
    op.create_table('private_sending_rates',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_sending_rates_company_id'), 'private_sending_rates', ['company_id'], unique=False)
    # ### end Alembic commands ###

    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.String()),
    )
    op.bulk_insert(
        permissions_table,
        [
            {
                "id": uuid.uuid4(),
                "code": PermissionCode.COLLABORATION_MANAGE.value,
                "description": PERMISSION_DESCRIPTIONS[PermissionCode.COLLABORATION_MANAGE],
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("DELETE FROM permissions WHERE code = :code").bindparams(
            code=PermissionCode.COLLABORATION_MANAGE.value
        )
    )
    op.drop_index(op.f('ix_private_sending_rates_company_id'), table_name='private_sending_rates')
    op.drop_table('private_sending_rates')
    op.drop_index(op.f('ix_collaboration_rate_history_collaboration_id'), table_name='collaboration_rate_history')
    op.drop_table('collaboration_rate_history')
    op.drop_index(op.f('ix_collaborations_target_company_id'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_initiator_company_id'), table_name='collaborations')
    op.drop_table('collaborations')
    # ### end Alembic commands ###
