"""add proofs table

Revision ID: 9c101344d01f
Revises: fe6d7ee8b52b
Create Date: 2026-07-06 16:54:16.182501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c101344d01f'
down_revision: Union[str, Sequence[str], None] = 'fe6d7ee8b52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proofs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(transfer_id, payment_id) = 1', name='ck_proofs_exactly_one_operation'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proofs_company_id'), 'proofs', ['company_id'], unique=False)
    op.create_index(op.f('ix_proofs_payment_id'), 'proofs', ['payment_id'], unique=False)
    op.create_index(op.f('ix_proofs_transfer_id'), 'proofs', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proofs_transfer_id'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_payment_id'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_company_id'), table_name='proofs')
    op.drop_table('proofs')
    # ### end Alembic commands ###
