"""phase4 national operations

Revision ID: a127642fd303
Revises: 012c10ff7436
Create Date: 2026-07-04 13:03:56.583646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a127642fd303'
down_revision: Union[str, Sequence[str], None] = '012c10ff7436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('national_operations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'EXCHANGE', 'REBALANCE', 'ADJUSTMENT', name='nationaloperationtype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'CANCELLED', 'CORRECTED', name='nationaloperationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('proof_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_of_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['national_operations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_operations_company_id'), 'national_operations', ['company_id'], unique=False)
    op.create_index(op.f('ix_national_operations_reference'), 'national_operations', ['reference'], unique=True)
    op.create_table('national_operation_lines',
    sa.Column('national_operation_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_out', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['national_operation_id'], ['national_operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_operation_lines_national_operation_id'), 'national_operation_lines', ['national_operation_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_national_operation_lines_national_operation_id'), table_name='national_operation_lines')
    op.drop_table('national_operation_lines')
    op.drop_index(op.f('ix_national_operations_reference'), table_name='national_operations')
    op.drop_index(op.f('ix_national_operations_company_id'), table_name='national_operations')
    op.drop_table('national_operations')
    # ### end Alembic commands ###
