"""phase7 transfers and collaborator balance

Revision ID: b7adc6877932
Revises: 1d2b3bca5059
Create Date: 2026-07-04 13:39:03.615650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7adc6877932'
down_revision: Union[str, Sequence[str], None] = '1d2b3bca5059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator_balance_movements',
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('debtor_company_id', sa.UUID(), nullable=False),
    sa.Column('creditor_company_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creditor_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['debtor_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborator_balance_movements_collaboration_id'), 'collaborator_balance_movements', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_collaborator_balance_movements_source_id'), 'collaborator_balance_movements', ['source_id'], unique=False)
    op.create_table('transfers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_phone', sa.String(length=32), nullable=False),
    sa.Column('send_mode', sa.Enum('CASH', 'WAVE', 'ORANGE_MONEY', 'BANK', 'OTHER', name='sendmode', native_enum=False, length=16), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('private_rate_used', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('collaborative_rate_used', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('converted_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='transferstatus', native_enum=False, length=16), nullable=False),
    sa.Column('proof_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_collaboration_id'), 'transfers', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_transfers_company_id'), 'transfers', ['company_id'], unique=False)
    op.create_index(op.f('ix_transfers_reference'), 'transfers', ['reference'], unique=True)
    op.create_table('transfer_status_history',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='transferstatus', native_enum=False, length=16), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='transferstatus', native_enum=False, length=16), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_status_history_transfer_id'), 'transfer_status_history', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_status_history_transfer_id'), table_name='transfer_status_history')
    op.drop_table('transfer_status_history')
    op.drop_index(op.f('ix_transfers_reference'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_company_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_collaboration_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_collaborator_balance_movements_source_id'), table_name='collaborator_balance_movements')
    op.drop_index(op.f('ix_collaborator_balance_movements_collaboration_id'), table_name='collaborator_balance_movements')
    op.drop_table('collaborator_balance_movements')
    # ### end Alembic commands ###
