"""add operation_type to private_sending_rates

Revision ID: c42c18998f51
Revises: 84ddfbfe8744
Create Date: 2026-07-07 16:38:12.381460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42c18998f51'
down_revision: Union[str, Sequence[str], None] = '84ddfbfe8744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_sending_rates', sa.Column('operation_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_sending_rates', 'operation_type')
    # ### end Alembic commands ###
