"""phase9 clients suppliers and debt tracking

Revision ID: f3c10ef14f77
Revises: 534f4ad3c025
Create Date: 2026-07-04 13:57:50.344494

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

NEW_PERMISSION_CODE = "client.manage"
NEW_PERMISSION_DESCRIPTION = "Gérer les clients et consulter leurs dettes"


# revision identifiers, used by Alembic.
revision: str = 'f3c10ef14f77'
down_revision: Union[str, Sequence[str], None] = '534f4ad3c025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'phone', name='uq_client_company_phone')
    )
    op.create_index(op.f('ix_clients_company_id'), 'clients', ['company_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_supplier_company_code')
    )
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_table('client_balance_movements',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_balance_movements_client_id'), 'client_balance_movements', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_balance_movements_source_id'), 'client_balance_movements', ['source_id'], unique=False)
    op.create_table('supplier_balance_movements',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEBT', 'PAYMENT', name='suppliermovementtype', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('proof_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_balance_movements_reference'), 'supplier_balance_movements', ['reference'], unique=True)
    op.create_index(op.f('ix_supplier_balance_movements_supplier_id'), 'supplier_balance_movements', ['supplier_id'], unique=False)
    op.add_column('payments', sa.Column('client_id', sa.UUID(), nullable=True))
    op.add_column('payments', sa.Column('client_debt_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.create_foreign_key(
        'fk_payments_client_id_clients', 'payments', 'clients', ['client_id'], ['id'], ondelete='RESTRICT'
    )
    op.add_column('transfers', sa.Column('client_id', sa.UUID(), nullable=True))
    op.add_column('transfers', sa.Column('client_debt_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.create_foreign_key(
        'fk_transfers_client_id_clients', 'transfers', 'clients', ['client_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###

    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.String()),
    )
    op.bulk_insert(
        permissions_table,
        [{"id": uuid.uuid4(), "code": NEW_PERMISSION_CODE, "description": NEW_PERMISSION_DESCRIPTION}],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("DELETE FROM permissions WHERE code = :code").bindparams(code=NEW_PERMISSION_CODE)
    )
    op.drop_constraint('fk_transfers_client_id_clients', 'transfers', type_='foreignkey')
    op.drop_column('transfers', 'client_debt_amount')
    op.drop_column('transfers', 'client_id')
    op.drop_constraint('fk_payments_client_id_clients', 'payments', type_='foreignkey')
    op.drop_column('payments', 'client_debt_amount')
    op.drop_column('payments', 'client_id')
    op.drop_index(op.f('ix_supplier_balance_movements_supplier_id'), table_name='supplier_balance_movements')
    op.drop_index(op.f('ix_supplier_balance_movements_reference'), table_name='supplier_balance_movements')
    op.drop_table('supplier_balance_movements')
    op.drop_index(op.f('ix_client_balance_movements_source_id'), table_name='client_balance_movements')
    op.drop_index(op.f('ix_client_balance_movements_client_id'), table_name='client_balance_movements')
    op.drop_table('client_balance_movements')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_clients_company_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
